apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ken-customer
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ken-customer
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: ken-config-map
          image: 'xuyingken/customer:v2'
          name: ken-customer-accounts
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5 