apiVersion: v1
kind: Service
metadata:
  name: ken-customer
  labels:
    name: ken-customer
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ken-customer
  type: LoadBalancer