apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ken-customer-accounts
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ken-customer-accounts
    spec:
      containers:
        - name: ken-customer-accounts
          image: 'xuyingken/customer-accounts:v2'
          ports:
            - containerPort: 8090
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5 