apiVersion: v1
kind: Service
metadata:
  name: ken-customer-accounts
  labels:
    name: ken-customer-accounts
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: ken-customer-accounts
  type: LoadBalancer